/*
 This file is part of the OdinMS Maple Story Server
 Copyright (C) 2008 Patrick Huy <patrick.huy@frz.cc>
 Matthias Butz <matze@odinms.de>
 Jan Christian Meyer <vimes@odinms.de>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as
 published by the Free Software Foundation version 3 as published by
 the Free Software Foundation. You may not use, modify or distribute
 this program under any other version of the GNU Affero General Public
 License.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net;

public enum SendOpcode {

    LOGIN_STATUS(0),
    GUEST_ID_LOGIN(1),
    SERVERSTATUS(2), // CHECK_USER_LIMIT_RESULT
    SET_ACCOUNT_RESULT(3), // "GENDER_DONE"
    CONFIRM_EULA_RESULT(4),
    CHECK_PINCODE(6),
    UPDATE_PINCODE(7),
    SERVERLIST(8),
    CHARLIST(9),
    SERVER_IP(10),
    CHAR_NAME_RESPONSE(11),
    ADD_NEW_CHAR_ENTRY(12),
    DELETE_CHAR_RESPONSE(13),
    CHANGE_CHANNEL(14),
    PING(15),
    AUTHEN_CODE_CHANGED(16),
    AUTHEN_MESSAGE(17),
    SECURITY_PACKET(18),
    GUARD_INSPECT_PROCESS(19),
    CHECK_CRC_RESULT(23),
    LAST_CONNECTED_WORLD(24),
    RECOMMENDED_WORLD_MESSAGE(25),

    /*CWvsContext::OnPacket*/
    INVENTORY_OPERATION(27),
    INVENTORY_GROW(28),
    STAT_CHANGED(29),
    GIVE_BUFF(30),
    CANCEL_BUFF(31),
    FORCED_STAT_SET(32),
    FORCED_STAT_RESET(33),
    UPDATE_SKILLS(34),
    SKILL_USE_RESULT(35),
    FAME_RESPONSE(37),
    SHOW_STATUS_INFO(38),
    MEMO_RESULT(39),
    MAP_TRANSFER_RESULT(40),
    ANTI_MACRO_RESULT(41),
    CLAIM_RESULT(43),
    CLAIM_AVAILABLE_TIME(44),
    CLAIM_STATUS_CHANGED(45),
    SET_TAMING_MOB_INFO(46),
    QUEST_CLEAR(47),
    ENTRUSTED_SHOP_CHECK_RESULT(48),
    SKILL_LEARN_ITEM_RESULT(49),
    GATHER_ITEM_RESULT(50),
    SORT_ITEM_RESULT(51),
    CHAR_INFO(55),
    PARTY_OPERATION(56),
    BUDDYLIST(57),
    GUILD_OPERATION(59),
    ALLIANCE_OPERATION(60),
    SPAWN_PORTAL(61),
    SERVERMESSAGE(62),
    INCUBATOR_RESULT(63),
    SHOP_SCANNER_RESULT(64),
    SHOP_LINK_RESULT(65),
    MARRIAGE_REQUEST(66),
    MARRIAGE_RESULT(67),
    WEDDING_GIFT_RESULT(68),
    NOTIFY_MARRIED_PARTNER_MAP_TRANSFER(69),
    CASH_PET_FOOD_RESULT(70),
    SET_WEEK_EVENT_MESSAGE(71),
    SET_POTION_DISCOUNT_RATE(72),
    BRIDLE_MOB_CATCH_FAIL(73),
    IMITATED_NPC_RESULT(74),
    IMITATED_NPC_DATA(75),
    LIMITED_NPC_DISABLE_INFO(76),
    DESTROY_SHOP_RESULT(77),
    FAKE_GM_NOTICE(78),//bad asses
    NEW_YEAR_CARD_RES(79),
    RANDOM_MORPH_RES(80),
    MONSTER_BOOK_SET_CARD(81), // not supported in EMS
    MONSTER_BOOK_SET_COVER(82), // not supported in EMS
    HOUR_CHANGED(83),
    MINIMAP_ON_OFF(84),
    CONSULT_AUTHKEY_UPDATE(85),
    CLASS_COMPETITION_AUTHKEY_UPDATE(86),
    WEB_BOARD_AUTHKEY_UPDATE(87),
    SESSION_VALUE(88),
    PARTY_VALUE(89),
    FIELD_SET_VARIABLE(90),
    BONUS_EXP_CHANGED(91), // pendant of spirit etc

    FAMILY_CHART_RESULT(92),
    FAMILY_INFO_RESULT(93),
    FAMILY_RESULT(94),
    FAMILY_JOIN_REQUEST(95),
    FAMILY_JOIN_REQUEST_RESULT(96),
    FAMILY_JOIN_ACCEPTED(97),
    FAMILY_PRIVILEGE_LIST(98),
    FAMILY_FAMOUS_POINT_INC_RESULT(99),
    FAMILY_NOTIFY_LOGIN_OR_LOGOUT(100), //? is logged in. LOLWUT
    FAMILY_SET_PRIVILEGE(101),
    FAMILY_SUMMON_REQUEST(102),

    NOTIFY_LEVELUP(103),
    NOTIFY_MARRIAGE(104),
    NOTIFY_JOB_CHANGE(105),
    SET_BUY_EQUIP_EXT(106),
    SET_PASSENGER_REQUEST(107), // recv companion: 111
    SCRIPT_PROGRESS_MESSAGE(108),
    DATA_CRC_CHECK_FAILED(109),
    DRAGON_BALL_BOX(110),
    SUCCESS_IN_USE_GACHAPON_BOX(111),
    AVATAR_MEGAPHONE_RESULT(112),//bot useless..
    SET_AVATAR_MEGAPHONE(113),
    CLEAR_AVATAR_MEGAPHONE(114),
    ASK_USER_WHETHER_USE_PAMS_SONG(115), // recv companion: 174
    MACRO_SYS_DATA_INIT(116),

    /*CStage::OnPacket*/
    SET_FIELD(117),
    SET_CASH_SHOP(118),
    
    /*CField::OnPacket*/
    SET_BACK_EFFECT(119),
    SET_MAP_OBJECT_VISIBLE(120),//CMapLoadable::OnSetMapObjectVisible O_O
    CLEAR_BACK_EFFECT(121),
    BLOCKED_MAP(122),//TransferFieldRequestIgnored
    BLOCKED_SERVER(123),
    FORCED_MAP_EQUIP(124),//FIELD_SPECIFIC_DATA
    MULTICHAT(125),
    WHISPER(126),
    //SPOUSE_CHAT(),
    SUMMON_ITEM_INAVAILABLE(127), //You can't use it in this map
    FIELD_EFFECT(128),
    //FIELD_OBSTACLE_ONOFF(0x8B),
    //FIELD_OBSTACLE_ONOFF_STATUS(0x8C),
    //FIELD_OBSTACLE_ALL_RESET(0x8D),
    BLOW_WEATHER(129),
    PLAY_JUKEBOX(130),
    ADMIN_RESULT(131),
    OX_QUIZ(133),//QUIZ
    GMEVENT_INSTRUCTIONS(134),//DESC
    CLOCK(135),
    CONTI_MOVE(136),
    CONTI_STATE(137),
    SET_QUEST_CLEAR(138),
    SET_QUEST_TIME(139),
    SET_OBJECT_STATE(140),
    STOP_CLOCK(141),
    ARIANT_ARENA_SHOW_RESULT(142),
    STALK_RESULT(143),
    MASSACRE_INC_GAUGE(144),
    MASSACRE_RESULT(145),
    QUICKSLOT_MAPPED_INIT(146),
    WARN_MESSAGE(147),

    SPAWN_PLAYER(148),
    REMOVE_PLAYER_FROM_MAP(149),
    CHATTEXT(150),
    CHALKBOARD(151),
    UPDATE_CHAR_BOX(152),
    SHOW_CONSUME_EFFECT(153),
    SHOW_SCROLL_EFFECT(154),

    SPAWN_PET(157),
    PET_EVOL(158),
    PET_TRANSFERFIELD(159),
    MOVE_PET(160),
    PET_CHAT(161),
    PET_NAMECHANGE(162),
    PET_SHOW(163),
    PET_COMMAND(164),
    SPAWN_SPECIAL_MAPOBJECT(165),
    REMOVE_SPECIAL_MAPOBJECT(166),
    MOVE_SUMMON(167),
    SUMMON_ATTACK(168),
    DAMAGE_SUMMON(169),
    SUMMON_SKILL(170),

    MOVE_PLAYER(175),
    CLOSE_RANGE_ATTACK(176),
    RANGED_ATTACK(177),
    MAGIC_ATTACK(178),
    ENERGY_ATTACK(179),
    SKILL_EFFECT(180),
    CANCEL_SKILL_EFFECT(181),
    DAMAGE_PLAYER(182),
    FACIAL_EXPRESSION(183),
    SHOW_ITEM_EFFECT(184),
    SHOW_UPGRADE_TOMB_EFFECT(185),
    SHOW_CHAIR(186),
    UPDATE_CHAR_LOOK(187),
    SHOW_FOREIGN_EFFECT(188),
    GIVE_FOREIGN_BUFF(189),
    CANCEL_FOREIGN_BUFF(190),
    UPDATE_PARTYMEMBER_HP(191),
    GUILD_NAME_CHANGED(192),
    GUILD_MARK_CHANGED(193),
    THROW_GRENADE(194),

    CANCEL_CHAIR(195), // SIT_RESULT
    SHOW_ITEM_GAIN_INCHAT(196),
    DOJO_WARP_UP(197),
    MESO_GIVE_SUCCEEDED(199),
    MESO_GIVE_FAILED(200),
    RANDOM_MESOBAG_SUCCEEDED(201),
    RANDOM_MESOBAG_FAILED(202),
    UPDATE_QUEST_INFO(203),
    PLAYER_HINT(206),
    OPEN_CLASS_COMPETITION_PAGE(211),
    OPEN_UI(212),
    OPEN_UI_WITH_OPTION(213),
    SET_DIRECTION_MODE(214),
    SET_STANDALONE_MODE(215),
    SPAWN_GUIDE(216),
    TALK_GUIDE(217),
    SHOW_COMBO(218),
    SET_RADIO_SCHEDULE(219),
    OPEN_SKILL_GUIDE(220),
    NOTICE_MSG(221),
    CHAT_MSG(222),
    USER_PASSIVE_MOVE(224),
    FOLLOW_CHARACTER_FAILED(225),
    COOLDOWN(226),

    SPAWN_MONSTER(228),
    KILL_MONSTER(229),
    SPAWN_MONSTER_CONTROL(230),
    MOVE_MONSTER(231),
    MOVE_MONSTER_RESPONSE(232),
    APPLY_MONSTER_STATUS(234),
    CANCEL_MONSTER_STATUS(235),
    RESET_MONSTER_ANIMATION(236),
    MOB_AFFECTED(237),
    DAMAGE_MONSTER(238),
    MOB_SPECIAL_EFFECT_BY_SKILL(239),
    SHOW_MONSTER_HP(242),
    MOB_CATCH_EFFECT(243),
    MOB_EFFECT_BY_ITEM(244),
    MOB_SPEAKING(245),

    SPAWN_NPC(248),
    REMOVE_NPC(249),
    SPAWN_NPC_REQUEST_CONTROLLER(250),
    NPC_ACTION(251),

    SPAWN_HIRED_MERCHANT(256),
    DESTROY_HIRED_MERCHANT(257),
    UPDATE_HIRED_MERCHANT(258),
    DROP_ITEM_FROM_MAPOBJECT(259),
    REMOVE_ITEM_FROM_MAP(261),
    KITE_MESSAGE(262),
    KITE(263),
    SPAWN_MIST(265),
    REMOVE_MIST(266),
    SPAWN_DOOR(267),
    REMOVE_DOOR(268),
    REACTOR_HIT(269),
    REACTOR_SPAWN(271),
    REACTOR_DESTROY(272),

    SNOWBALL_STATE(273),
    HIT_SNOWBALL(274),
    SNOWBALL_MESSAGE(275),
    LEFT_KNOCK_BACK(276),
    COCONUT_HIT(277),
    COCONUT_SCORE(278),
    GUILD_BOSS_HEALER_MOVE(279),
    GUILD_BOSS_PULLEY_STATE_CHANGE(280),
    MONSTER_CARNIVAL_START(281),
    MONSTER_CARNIVAL_OBTAINED_CP(282),
    MONSTER_CARNIVAL_PARTY_CP(283),
    MONSTER_CARNIVAL_SUMMON(284),
    MONSTER_CARNIVAL_MESSAGE(285),
    MONSTER_CARNIVAL_DIED(286),
    MONSTER_CARNIVAL_LEAVE(287),
    ARIANT_ARENA_USER_SCORE(289),
    SHEEP_RANCH_INFO(290),
    SHEEP_RANCH_CLOTHES(291),
    ARIANT_SCORE(292),
    HORNTAIL_CAVE(293),
    ZAKUM_SHRINE(294),

    NPC_TALK(295),
    OPEN_NPC_SHOP(296),
    CONFIRM_SHOP_TRANSACTION(297),
    ADMIN_SHOP_MESSAGE(298),//lame :P
    ADMIN_SHOP(299),
    STORAGE(300),
    FREDRICK_MESSAGE(301),
    FREDRICK(302),
    RPS_GAME(303),
    MESSENGER(304),
    PLAYER_INTERACTION(305),

    TOURNAMENT(306),
    TOURNAMENT_MATCH_TABLE(307),
    TOURNAMENT_SET_PRIZE(308),
    TOURNAMENT_UEW(309),
    TOURNAMENT_CHARACTERS(310),//they never coded this :|

    WEDDING_PROGRESS(311),//byte step, int groomid, int brideid
    WEDDING_CEREMONY_END(312),

    PARCEL(313),

    CHARGE_PARAM_RESULT(314),
    QUERY_CASH_RESULT(315),
    CASHSHOP_OPERATION(316),

    KEYMAP(323),
    AUTO_HP_POT(324),
    AUTO_MP_POT(325),

    VICIOUS_HAMMER(329);

    private int value = -2;

    private SendOpcode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
